services:
  rust-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-proxy
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      - ENABLE_CORS=false
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8082']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
