services:
  rust-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8082:8082'
    environment:
      - ENABLE_CORS=false
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8082 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default
      - dokploy-network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rust-proxy.rule=Host(`cors.animehi.live`)'
      - 'traefik.http.routers.rust-proxy.entrypoints=web,websecure'
      - 'traefik.http.services.rust-proxy.loadbalancer.server.port=8082'
      - 'traefik.docker.network=dokploy-network'

networks:
  dokploy-network:
    external: true
    name: dokploy-network
