services:
  rust-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - '8082'
    environment:
      - ENABLE_CORS=false
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8082 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
